name: Send report

on:
  push:
    branches:
      - main

jobs:
  report:
    name: Send report
    runs-on: ubuntu-latest
    env:
      TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ vars.TELEGRAM_CHAT_ID }}
      TELEGRAM_TOPIC_ID: ${{ vars.TELEGRAM_TOPIC_ID }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run
        run: gh --version
